config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :links do 
  	member do 
  		put "like", to: "links#upvote"
  		put "dislike", to: "links#downvote"
  	end
    resources :comments
  end
  root to: "links#index"
  #HTTP POST method is used to prevent showing params in the data in the URL.
  post 'downloads/download' => 'downloads#download', as: :download
  post 'downloads/show_options' => 'downloads#show_options', as: :show_options
  post 'downloads/hide_options' => 'downloads#hide_options', as: :hide_options
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
	respond_to :html, :js

  def home
  end

	def show_options
	end

	def hide_options
	end

	def download
		if params[:data]
      send_data render_to_string(partial: 'downloads/download/data'),
                type: 'text/plain; charset=UTF-8;',
                filename: "Data #{Time.current.to_formatted_s(:db)}.txt"
    elsif params[:sample]
      send_data render_to_string(partial: 'downloads/download/sample'),
                type: 'text/plain; charset=UTF-8;',
                filename: "Sample #{Time.current.to_formatted_s(:db)}.txt"
    elsif params[:demo]
      send_data render_to_string(partial: 'downloads/download/demo'),
                type: 'text/plain; charset=UTF-8;',
                filename: "Demo #{Time.current.to_formatted_s(:db)}.txt"
        end
	end 
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/views/downloads/_download_options.html.erb
<div id="download_options">
 <%= link_to "Downloads", show_options_path,
 :remote => true,
 :method => "post" %>
</div>

app/views/downloads/_downloads_list.html.erb
<h1> Downloads </h1>
<ul>
<li><%= link_to "Telangana welfare schemes", download_path(data: true), :method => "post" %></li>
<li><%= link_to "Andhra Pradesh Welfare schemes", download_path(sample: true), :method => "post" %></li>
<li><%= link_to "Recent Govt GO's", download_path(demo: true), :method => "post" %></li>
</ul>
<%= button_to "Close", hide_options_path,
:remote => true,
:method => "post" %>

app/views/downloads/hide_options.js.erb
$('#download_options').html("<%= j (render 'downloads/download_options') %>");

app/views/downloads/show_options.js.erb
$('#download_options').html("<%= j (render 'downloads/downloads_list') %>");
$('#download_options').slideDown(350);